// [XPLAT] migrated from net48 — see MIGRATION_DOCS/TRANSITION_MAP.md
//
// Field-file load -> save -> byte-compare parity suite (AAP §0.6.4 "FieldRoundTripTests").
//
// PROOF OBLIGATION
// ----------------
// The net48/WinForms -> net8.0/Avalonia migration must not let the field-file formats under
// SourceCode/GPS/IO/ drift, and must not let the cross-OS hazards of AAP §0.6.5 (end-of-line,
// culture/decimal-separator, path separators) corrupt a single byte. For every field artifact this
// fixture loads a golden file captured from the Windows/net48 baseline, stages it into a temporary
// field directory under the handler's REAL on-disk file name, drives the production AgOpenGPS.IO
// handler's Load then Save (re-emitting through the genuine serializer), reads the re-saved file back
// as RAW BYTES, and asserts it is byte-for-byte identical to the golden.
//
// WHY THE STATIC AgOpenGPS.IO HANDLERS (NOT FieldIoService)
// ---------------------------------------------------------
// The extracted AgOpenGPS.Services.FieldIoService orchestrator requires a heavy domain object graph
// (FormGPS / ApplicationCore collaborators) that cannot be assembled in a unit test. The static
// AgOpenGPS.IO.*Files handlers carry the actual serialization logic and are pure file-in / file-out,
// so they exercise the real production format directly and remain cleanly callable here.
//
// ENFORCING GOLDENS (final gate)
// ------------------------------
// The field goldens are committed under Parity/Golden/Field and the byte-contract is ENFORCED: each
// golden-consuming test calls LoadRequiredGolden, which FAILS (not Ignores) when its artifact is absent.
// A missing golden means contract C2 (field-file byte formats) is unproven, so the suite must surface
// red rather than green-with-skips. The goldens are byte-identical across windows / ubuntu / macos
// (including osx-arm64) because the Parity tree is pinned `-text` in .gitattributes (no CRLF<->LF
// normalization); full tri-OS execution evidence is recorded in MIGRATION_DOCS/PARITY_REPORT.md.
//
// This extends the round-trip byte-compare pattern proven in
// SourceCode/AgLibrary.Tests/Settings/XmlSettingsHandlerTests.cs, upgraded from File.ReadAllText to
// File.ReadAllBytes so the comparison is byte-exact rather than text-equivalent.
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using AgOpenGPS.IO;
using NUnit.Framework;

namespace AgOpenGPS.Tests.Parity
{
    /// <summary>
    /// Byte-exact load -> save round-trip parity tests for the <c>SourceCode/GPS/IO/</c> field-file
    /// handlers. Every test stages a frozen golden, re-emits it through the production
    /// <see cref="AgOpenGPS.IO"/> serializer, and asserts the regenerated bytes equal the golden. The
    /// goldens are committed and the byte-contract is ENFORCED: a test FAILS (it does not self-skip) when
    /// its required golden is absent, so contract C2 cannot silently regress at the final gate.
    /// </summary>
    [TestFixture]
    public class FieldRoundTripTests
    {
        /// <summary>
        /// Per-test input directory: the golden is staged here under the handler's real on-disk file
        /// name so the production <c>Load</c> reads exactly what the baseline wrote.
        /// </summary>
        private string _fieldDir;

        /// <summary>
        /// Per-test output directory: the production <c>Save</c> re-emits here, isolated from the staged
        /// input so an append-style writer can never interleave with the staged golden bytes.
        /// </summary>
        private string _outDir;

        /// <summary>
        /// [XPLAT] Forces <see cref="CultureInfo.InvariantCulture"/> for the whole fixture so the only
        /// correct decimal separator is a period regardless of the host locale. The IO handlers already
        /// format/parse with <see cref="CultureInfo.InvariantCulture"/>; pinning invariant culture here
        /// makes any regression to culture-sensitive formatting (a comma-decimal locale such as de-DE or
        /// fr-FR on Linux/macOS — AAP §0.6.5) surface deterministically. Mirrors the sibling Parity fixtures.
        /// </summary>
        [OneTimeSetUp]
        public void ForceInvariantCulture()
        {
            CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;
            CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture;
        }

        /// <summary>
        /// Creates fresh, uniquely named input and output directories under
        /// <see cref="Path.GetTempPath"/> so no test ever touches a real field location and parallel
        /// test runs never collide.
        /// </summary>
        [SetUp]
        public void CreateTempDirectories()
        {
            _fieldDir = Path.Combine(
                Path.GetTempPath(), "AgOpenGPS_FieldParity_in_" + Guid.NewGuid().ToString("N"));
            _outDir = Path.Combine(
                Path.GetTempPath(), "AgOpenGPS_FieldParity_out_" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(_fieldDir);
            Directory.CreateDirectory(_outDir);
        }

        /// <summary>
        /// Removes the per-test temp directories. Cleanup is best-effort: a leaked temp directory must
        /// never turn a parity assertion red.
        /// </summary>
        [TearDown]
        public void RemoveTempDirectories()
        {
            TryDeleteDirectory(_fieldDir);
            TryDeleteDirectory(_outDir);
        }

        // =====================================================================================
        // Phase B — one byte-compare round-trip [Test] per field artifact.
        // =====================================================================================

        /// <summary>Boundary rings round-trip through <see cref="BoundaryFiles"/> (Boundary.txt, header <c>$Boundary</c>).</summary>
        [Test]
        public void Boundary_RoundTrip_IsByteIdentical()
        {
            byte[] golden = LoadRequiredGolden("Boundary.txt");
            StageGolden(golden, "Boundary.txt");

            // Empty/edge case is handled naturally: a "$Boundary\n" golden loads to an empty list and
            // re-saves to "$Boundary\n", so a minimal golden still round-trips.
            List<CBoundaryList> boundaries = BoundaryFiles.Load(_fieldDir);
            BoundaryFiles.Save(_outDir, boundaries);

            byte[] saved = File.ReadAllBytes(Path.Combine(_outDir, "Boundary.txt"));
            Assert.That(saved, Is.EqualTo(golden));
        }

        /// <summary>
        /// AB / curve tracks round-trip through <see cref="TrackFiles"/>. The golden is named
        /// <c>Tracks.txt</c> but the handler's real on-disk file is <c>TrackLines.txt</c> (header
        /// <c>$TrackLines</c>), so the golden is staged under the on-disk name before Load/Save.
        /// </summary>
        [Test]
        public void Track_RoundTrip_IsByteIdentical()
        {
            byte[] golden = LoadRequiredGolden("Tracks.txt");
            StageGolden(golden, "TrackLines.txt");

            List<CTrk> tracks = TrackFiles.Load(_fieldDir);
            TrackFiles.Save(_outDir, tracks);

            byte[] saved = File.ReadAllBytes(Path.Combine(_outDir, "TrackLines.txt"));
            Assert.That(saved, Is.EqualTo(golden));
        }

        /// <summary>
        /// Applied-section coverage patches round-trip through <see cref="SectionsFiles"/> (Sections.txt,
        /// header-less count-prefixed <c>vec3</c> blocks). The writer is append-style, so the re-save is
        /// <see cref="SectionsFiles.CreateEmpty"/> followed by <see cref="SectionsFiles.Append"/>.
        /// </summary>
        [Test]
        public void Sections_RoundTrip_IsByteIdentical()
        {
            byte[] golden = LoadRequiredGolden("Sections.txt");
            StageGolden(golden, "Sections.txt");

            List<List<vec3>> patches = SectionsFiles.Load(_fieldDir);

            SectionsFiles.CreateEmpty(_outDir);
            SectionsFiles.Append(_outDir, patches.ConvertAll(p => (IReadOnlyList<vec3>)p));

            byte[] saved = File.ReadAllBytes(Path.Combine(_outDir, "Sections.txt"));
            Assert.That(saved, Is.EqualTo(golden));
        }

        /// <summary>
        /// Field flags round-trip through <see cref="FlagsFiles"/> (Flags.txt, header <c>$Flags</c>).
        /// Additionally asserts the re-saved text begins with the <c>$Flags</c> header and that a known
        /// double serializes with a period decimal separator (the InvariantCulture guard of AAP §0.6.5).
        /// </summary>
        [Test]
        public void Flags_RoundTrip_IsByteIdentical()
        {
            byte[] golden = LoadRequiredGolden("Flags.txt");
            StageGolden(golden, "Flags.txt");

            List<CFlag> flags = FlagsFiles.Load(_fieldDir);
            FlagsFiles.Save(_outDir, flags);

            byte[] saved = File.ReadAllBytes(Path.Combine(_outDir, "Flags.txt"));
            Assert.That(saved, Is.EqualTo(golden));

            string savedText = System.Text.Encoding.UTF8.GetString(saved);
            Assert.That(savedText.StartsWith("$Flags", StringComparison.Ordinal), Is.True);

            // When the golden carries at least one flag, prove its latitude serialized with a PERIOD
            // decimal — a comma-decimal locale regression would make the period form disappear.
            if (flags.Count > 0)
            {
                AssertInvariantPeriodFormat(saved, flags[0].latitude);
            }
        }

        /// <summary>
        /// Contour-following recorded strips round-trip through <see cref="ContourFiles"/> (Contour.txt,
        /// header <c>$Contour</c>). The writer is append-style, so the re-save is
        /// <see cref="ContourFiles.CreateFile"/> (writes the header) followed by <see cref="ContourFiles.Append"/>.
        /// </summary>
        [Test]
        public void Contour_RoundTrip_IsByteIdentical()
        {
            byte[] golden = LoadRequiredGolden("Contour.txt");
            StageGolden(golden, "Contour.txt");

            List<List<vec3>> patches = ContourFiles.Load(_fieldDir);

            ContourFiles.CreateFile(_outDir);
            ContourFiles.Append(_outDir, patches.ConvertAll(p => (IReadOnlyList<vec3>)p));

            byte[] saved = File.ReadAllBytes(Path.Combine(_outDir, "Contour.txt"));
            Assert.That(saved, Is.EqualTo(golden));
        }

        /// <summary>
        /// Per-boundary headland geometry round-trips through <see cref="HeadlandFiles"/> (Headland.txt,
        /// header <c>$Headland</c>). The handler reads via <see cref="HeadlandFiles.AttachLoad"/>, which
        /// attaches headland lines onto an existing boundary list, so the boundaries are first sourced
        /// from the companion <c>Boundary.txt</c> golden (Headland.txt is always captured alongside the
        /// Boundary.txt it indexes into). Requires both goldens; if either is absent the test FAILS.
        /// </summary>
        [Test]
        public void Headland_RoundTrip_IsByteIdentical()
        {
            byte[] boundaryGolden = LoadRequiredGolden("Boundary.txt");
            byte[] headlandGolden = LoadRequiredGolden("Headland.txt");

            StageGolden(boundaryGolden, "Boundary.txt");
            StageGolden(headlandGolden, "Headland.txt");

            List<CBoundaryList> boundaries = BoundaryFiles.Load(_fieldDir);
            HeadlandFiles.AttachLoad(_fieldDir, boundaries);
            HeadlandFiles.Save(_outDir, boundaries);

            byte[] saved = File.ReadAllBytes(Path.Combine(_outDir, "Headland.txt"));
            Assert.That(saved, Is.EqualTo(headlandGolden));
        }

        /// <summary>
        /// Headland-tracking guidance paths round-trip through <see cref="HeadlinesFiles"/>
        /// (Headlines.txt, header <c>$HeadLines</c>).
        /// </summary>
        [Test]
        public void Headlines_RoundTrip_IsByteIdentical()
        {
            byte[] golden = LoadRequiredGolden("Headlines.txt");
            StageGolden(golden, "Headlines.txt");

            List<CHeadPath> headPaths = HeadlinesFiles.Load(_fieldDir);
            HeadlinesFiles.Save(_outDir, headPaths);

            byte[] saved = File.ReadAllBytes(Path.Combine(_outDir, "Headlines.txt"));
            Assert.That(saved, Is.EqualTo(golden));
        }

        /// <summary>
        /// Tramline geometry round-trips through <see cref="TramFiles"/> (Tram.txt, header <c>$Tram</c>).
        /// <see cref="TramFiles.Load"/> returns a <c>TramData</c> DTO (outer ring, inner ring, optional
        /// lines) which is re-emitted through the multi-argument <see cref="TramFiles.Save"/>.
        /// </summary>
        [Test]
        public void Tram_RoundTrip_IsByteIdentical()
        {
            byte[] golden = LoadRequiredGolden("Tram.txt");
            StageGolden(golden, "Tram.txt");

            TramFiles.TramData data = TramFiles.Load(_fieldDir);
            TramFiles.Save(
                _outDir,
                data.Outer,
                data.Inner,
                data.Lines.ConvertAll(l => (IReadOnlyList<vec2>)l));

            byte[] saved = File.ReadAllBytes(Path.Combine(_outDir, "Tram.txt"));
            Assert.That(saved, Is.EqualTo(golden));
        }

        /// <summary>
        /// Recorded driving path round-trips through <see cref="RecPathFiles"/> (RecPath.txt, header
        /// <c>$RecPath</c>).
        /// </summary>
        [Test]
        public void RecPath_RoundTrip_IsByteIdentical()
        {
            byte[] golden = LoadRequiredGolden("RecPath.txt");
            StageGolden(golden, "RecPath.txt");

            List<CRecPathPt> recList = RecPathFiles.Load(_fieldDir);
            RecPathFiles.Save(_outDir, recList);

            byte[] saved = File.ReadAllBytes(Path.Combine(_outDir, "RecPath.txt"));
            Assert.That(saved, Is.EqualTo(golden));
        }

        /// <summary>
        /// Elevation log round-trips through <see cref="ElevationFiles"/> (Elevation.txt). The handler is
        /// asymmetric — <see cref="ElevationFiles.Load"/> returns the raw lines while
        /// <see cref="ElevationFiles.CreateHeader"/> + <see cref="ElevationFiles.Append"/> write the file —
        /// so the re-save reconstructs the canonical header (timestamp + StartFix parsed back out of the
        /// golden) through the real writer and re-appends any post-column-header grid rows. A header-only
        /// golden (elevation logging off, the default) round-trips exactly.
        /// </summary>
        [Test]
        public void Elevation_RoundTrip_IsByteIdentical()
        {
            byte[] golden = LoadRequiredGolden("Elevation.txt");
            StageGolden(golden, "Elevation.txt");

            ElevationFiles.ElevationData data = ElevationFiles.Load(_fieldDir);
            List<string> raw = data.RawLines;

            Assert.That(raw, Is.Not.Empty,
                "Elevation golden contained no readable lines; cannot reconstruct via ElevationFiles.");

            DateTime timestamp = DateTime.ParseExact(
                raw[0], "yyyy-MMMM-dd hh:mm:ss tt", CultureInfo.InvariantCulture);

            int startFixIndex = raw.FindIndex(l => l.Trim() == "StartFix");
            bool startFixOk = startFixIndex >= 0 && startFixIndex < raw.Count - 1;
            Assert.That(startFixOk, Is.True,
                "Elevation golden is missing a 'StartFix' marker followed by a lat,lon line.");

            string[] originParts = raw[startFixIndex + 1].Split(',');
            double lat = double.Parse(originParts[0], CultureInfo.InvariantCulture);
            double lon = double.Parse(originParts[1], CultureInfo.InvariantCulture);
            var startFix = new AgOpenGPS.Core.Models.Wgs84(lat, lon);

            ElevationFiles.CreateHeader(_outDir, timestamp, startFix);

            // Re-append any elevation grid samples that follow the "Latitude,Longitude,..." column header,
            // using the same per-line newline CreateHeader's WriteLine emits so the file stays consistent.
            int columnHeaderIndex = raw.FindIndex(l => l.StartsWith("Latitude", StringComparison.Ordinal));
            if (columnHeaderIndex >= 0 && columnHeaderIndex < raw.Count - 1)
            {
                List<string> gridRows = raw.GetRange(
                    columnHeaderIndex + 1, raw.Count - columnHeaderIndex - 1);
                string gridText = string.Join(Environment.NewLine, gridRows) + Environment.NewLine;
                ElevationFiles.Append(_outDir, gridText);
            }

            byte[] saved = File.ReadAllBytes(Path.Combine(_outDir, "Elevation.txt"));
            Assert.That(saved, Is.EqualTo(golden));
        }

        /// <summary>
        /// Field-plane origin round-trips through <see cref="FieldPlaneFiles"/>. The golden is named
        /// <c>FieldPlane.txt</c> but the handler's real on-disk file is <c>Field.txt</c>.
        /// <see cref="FieldPlaneFiles.LoadOrigin"/> returns only the WGS84 origin, so the creation
        /// timestamp is parsed back out of the golden's first line and the file is re-emitted through the
        /// real <see cref="FieldPlaneFiles.Save"/>.
        /// </summary>
        [Test]
        public void FieldPlane_RoundTrip_IsByteIdentical()
        {
            byte[] golden = LoadRequiredGolden("FieldPlane.txt");
            StageGolden(golden, "Field.txt");

            var origin = FieldPlaneFiles.LoadOrigin(_fieldDir);

            DateTime timestamp = DateTime.ParseExact(
                FirstLine(golden), "yyyy-MMMM-dd hh:mm:ss tt", CultureInfo.InvariantCulture);

            FieldPlaneFiles.Save(_outDir, timestamp, origin);

            byte[] saved = File.ReadAllBytes(Path.Combine(_outDir, "Field.txt"));
            Assert.That(saved, Is.EqualTo(golden));
        }

        // =====================================================================================
        // Helpers (cross-OS golden resolution, staging, invariant-culture and cleanup utilities).
        // =====================================================================================

        /// <summary>
        /// [XPLAT] Resolves a Field golden next to the test assembly (copied there by the
        /// <c>AgOpenGPS.Tests.csproj</c> <c>Parity\Golden\**\*</c> rule) using
        /// <see cref="TestContext.CurrentContext"/>.<c>TestDirectory</c> and <see cref="Path.Combine"/>
        /// so resolution is correct and case-stable on Windows, Linux and macOS. The field goldens are a
        /// committed, ENFORCING byte-contract: when the artifact is absent the test FAILS (it does not
        /// self-skip). This is the final-gate enforcement of behavior-frozen contract C2 (field-file byte
        /// formats) — a missing golden means the field byte-contract is unproven, which must surface red.
        /// </summary>
        /// <param name="fileName">The golden file name within <c>Parity/Golden/Field</c>.</param>
        /// <returns>The raw golden bytes.</returns>
        private static byte[] LoadRequiredGolden(string fileName)
        {
            string path = Path.Combine(
                TestContext.CurrentContext.TestDirectory, "Parity", "Golden", "Field", fileName);

            if (!File.Exists(path))
            {
                Assert.Fail(
                    $"Required field golden is missing: {path}. The field byte-contract (AAP contract C2) " +
                    "cannot be proven without it. Capture the baseline artifact and commit it under " +
                    "SourceCode/AgOpenGPS.Tests/Parity/Golden/Field/.");
            }

            return File.ReadAllBytes(path);
        }

        /// <summary>
        /// Writes the golden bytes verbatim into the per-test input directory under the handler's real
        /// on-disk field-file name, so the production <c>Load</c> reads exactly the captured baseline bytes.
        /// </summary>
        /// <param name="goldenBytes">The golden content to stage.</param>
        /// <param name="onDiskFileName">The real field-file name the handler reads (e.g. <c>TrackLines.txt</c>).</param>
        /// <returns>The full staged path (built with <see cref="Path.Combine"/>).</returns>
        private string StageGolden(byte[] goldenBytes, string onDiskFileName)
        {
            string path = Path.Combine(_fieldDir, onDiskFileName);
            File.WriteAllBytes(path, goldenBytes);
            return path;
        }

        /// <summary>
        /// Asserts <paramref name="sampleValue"/> appears in <paramref name="textBytes"/> in its
        /// <see cref="CultureInfo.InvariantCulture"/> (period decimal) form. Under a comma-decimal host
        /// locale the value would serialize as "53,12" and the period form would be ABSENT, so a
        /// regression to culture-sensitive formatting fails this assertion (AAP §0.6.5).
        /// </summary>
        private static void AssertInvariantPeriodFormat(byte[] textBytes, double sampleValue)
        {
            string text = System.Text.Encoding.UTF8.GetString(textBytes);
            string invariant = sampleValue.ToString(CultureInfo.InvariantCulture);
            Assert.That(text.Contains(invariant, StringComparison.Ordinal), Is.True,
                $"Expected InvariantCulture period-decimal form '{invariant}' in the serialized output.");
        }

        /// <summary>
        /// Returns the first line of a UTF-8 byte buffer (newline excluded, trailing CR trimmed) without
        /// allocating intermediate line arrays — used to recover a writer-emitted timestamp header line.
        /// </summary>
        private static string FirstLine(byte[] utf8Bytes)
        {
            string text = System.Text.Encoding.UTF8.GetString(utf8Bytes);
            int newlineIndex = text.IndexOf('\n');
            string line = newlineIndex >= 0 ? text.Substring(0, newlineIndex) : text;
            return line.TrimEnd('\r');
        }

        /// <summary>
        /// Deletes a temp directory tree, swallowing IO failures so cleanup never fails a parity result.
        /// </summary>
        private static void TryDeleteDirectory(string directory)
        {
            try
            {
                if (!string.IsNullOrEmpty(directory) && Directory.Exists(directory))
                {
                    Directory.Delete(directory, true);
                }
            }
            catch (IOException)
            {
                // Best-effort cleanup; a leaked temp directory must never break a test result.
            }
            catch (UnauthorizedAccessException)
            {
                // Same rationale: a permission hiccup during cleanup is not a parity failure.
            }
        }
    }
}
