// [XPLAT] migrated from net48/WinForms — see MIGRATION_DOCS/TRANSITION_MAP.md
using System.Threading.Tasks;
using Avalonia.Controls;
using Avalonia.Interactivity;

namespace AgOpenGPS.Updater.Forms
{
    /// <summary>
    /// [XPLAT] Release-notes popup for the AgOpenGPS Updater. Avalonia reimplementation of the
    /// WinForms <c>FormReleaseNotes</c> (Forms/FormReleaseNotes.cs). The single static helper fills
    /// the header title and the read-only notes box and shows the window modally over its owner.
    /// </summary>
    /// <remarks>
    /// Behavioral parity contract with the WinForms original:
    /// <list type="bullet">
    ///   <item>The window <see cref="Window.Title"/> is set to the caller-supplied title.</item>
    ///   <item>The header label reads <c>"Release Notes - {version}"</c>.</item>
    ///   <item>Empty/blank notes fall back to the literal <c>"No release notes available."</c>.</item>
    /// </list>
    /// The only intentional change is asynchrony: WinForms <c>ShowDialog</c> blocked, whereas the
    /// Avalonia modal <c>ShowDialog</c> is awaited (the caller in FormUpdate.axaml.cs awaits this
    /// helper). The public API is kept deliberately string-based (title/version/releaseNotes) to
    /// match the existing caller, which already extracts those strings from its release model.
    /// </remarks>
    public partial class FormReleaseNotes : Window
    {
        /// <summary>
        /// Initializes the window and loads the XAML defined in
        /// <c>FormReleaseNotes.axaml</c> (which provides the named controls
        /// <c>LblTitle</c>, <c>TxtNotes</c>, and <c>BtnClose</c>).
        /// </summary>
        public FormReleaseNotes()
        {
            // [XPLAT] InitializeComponent + the typed x:Name fields are generated by the Avalonia
            // XAML source generator from FormReleaseNotes.axaml (replaces the WinForms designer).
            InitializeComponent();
        }

        /// <summary>
        /// Displays the release notes in a modal dialog owned by <paramref name="owner"/>.
        /// </summary>
        /// <param name="owner">
        /// The owning Avalonia <see cref="Window"/> (FormUpdate passes <c>this</c>). When
        /// <see langword="null"/> the popup is shown non-modally, preserving the WinForms
        /// fallback to a parent-less <c>ShowDialog()</c>.
        /// </param>
        /// <param name="title">Window title text.</param>
        /// <param name="version">Version string rendered in the header as <c>"Release Notes - {version}"</c>.</param>
        /// <param name="releaseNotes">
        /// Release-notes body. When <see langword="null"/> or empty, the fallback
        /// <c>"No release notes available."</c> is shown instead.
        /// </param>
        /// <returns>A task that completes when the modal dialog is closed.</returns>
        public static async Task ShowReleaseNotes(Window owner, string title, string version, string releaseNotes)
        {
            // [XPLAT] Replaces the WinForms `using (var dialog = new FormReleaseNotes())` block.
            // Avalonia windows are not IDisposable; the dialog is reclaimed once it closes.
            var dialog = new FormReleaseNotes
            {
                Title = title
            };

            // [XPLAT] Parity: WinForms set dialog.lblTitle.Text / dialog.txtNotes.Text directly.
            dialog.LblTitle.Text = $"Release Notes - {version}";
            dialog.TxtNotes.Text = !string.IsNullOrEmpty(releaseNotes) ? releaseNotes : "No release notes available.";

            // [XPLAT] WinForms chose ShowDialog(parent) vs ShowDialog() based on a live parent;
            // here a non-null owner yields a modal dialog (WindowStartupLocation=CenterOwner in the
            // XAML reproduces StartPosition=CenterParent), otherwise the popup is shown standalone.
            if (owner != null)
            {
                await dialog.ShowDialog(owner);
            }
            else
            {
                dialog.Show();
            }
        }

        /// <summary>
        /// Closes the popup. Wired to the footer <c>BtnClose</c> button's
        /// <c>Click</c> event in <c>FormReleaseNotes.axaml</c>.
        /// </summary>
        private void BtnClose_Click(object sender, RoutedEventArgs e) => Close();
    }
}
